### ISSUE TITLE
Icon invisible if not on darkmode

### ISSUE THREAD

**Issue by sandercox** [sandercox/worktree-status#1]
Menu bar icon is almost invisible on macOS when not running in Dark Mode

**Comment by stijnfrishert** [comment]
Same goes for the .dmg and the icon in the finder, btw :)

![image](https://github.com/user-attachments/assets/ef0e6d41-90ea-40f5-84af-1efb5566156f)

**Comment by stijnfrishert** [comment]
Just downloaded 0.2.3, but the icon's still white?

![image](https://github.com/user-attachments/assets/d3b7404f-b7ce-4cb3-804f-23db860922bb)

Might be something in my OS cache, though? 🤷

**Comment by sandercox** [comment]
hmm the outline indeed got 'removed' or wasn't visible. The SVG was very low resolution so my changes made in Illustrator didn't really catch on to it. Update the SVG canvas size and did somefixup on the icon should be much better now with [v0.2.4](https://github.com/sandercox/worktree-status/releases/tag/v0.2.4)
