### ISSUE TITLE
Hide the pop-up when the tray icon is pressed again

### ISSUE THREAD

**Issue by stijnfrishert** [sandercox/worktree-status#6]
Pressing the tray icon once opens the pop-up. I clicked it again, expecting it to hide, but it didn't :)

**Comment by sandercox** [comment]
It did hide if you click anywhere else (having the dialog loose focus) that worked in my mind-set. But having this as an addition seems fair.

**Comment by stijnfrishert** [comment]
> It did hide if you click anywhere else (having the dialog loose focus) that worked in my mind-set. But having this as an addition seems fair.

Yeah, that does work. I guess it's in my muscle memory to re-click the icon sometimes.
